### CREATE
POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "NI",
    "content": "GGA"
}

### READ
GET http://localhost:3000/posts

### READ DETAIL
GET http://localhost:3000/posts/5

### UPDATE
PUT http://localhost:3000/posts/2
Content-Type: application/json

{
    "title": "PUSSYCLATTTTTT",
    "content": "PYATTTTTT"
}

### DELETE
DELETE http://localhost:3000/posts/1